image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - mkdir -p ./public/.well-known/acme-challenge
  - echo '_XEB2SQAHV5bQlZ-q5ti_psHjZjbOHApMT_42Z_t-cg.TfcYkRMGJmAIGD8_iBXTt-N66Oh6qAM57HUoAoDkxvQ' > ./public/.well-known/acme-challenge/_XEB2SQAHV5bQlZ-q5ti_psHjZjbOHApMT_42Z_t-cg
  artifacts:
    paths:
    - public
  only:
  - master
