image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/3TQDcS0aqat3JJS3YIx5nAyqgknqjfm_n5c3DuiSnPk.html ./public/.well-known/acme-challenge/3TQDcS0aqat3JJS3YIx5nAyqgknqjfm_n5c3DuiSnPk
  - cp ./public/.well-known/acme-challenge/7KtJzn6sKagmhhc3QRYlqzNonL3cWy-kZwKrOxnF5BI.html ./public/.well-known/acme-challenge/7KtJzn6sKagmhhc3QRYlqzNonL3cWy-kZwKrOxnF5BI
  artifacts:
    paths:
    - public
  only:
  - master
