image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./public/.well-known/acme-challenge/_3Frd8eckMdDu-19tCOlwwYKBgf9GY4Y_h4RcqsN9M0.html ./public/.well-known/acme-challenge/_3Frd8eckMdDu-19tCOlwwYKBgf9GY4Y_h4RcqsN9M0
  - cp ./public/.well-known/acme-challenge/G8wKiMv6onF24uN6oprzCW8HciezCMdqpnX-d4jKz5k.html ./public/.well-known/acme-challenge/G8wKiMv6onF24uN6oprzCW8HciezCMdqpnX-d4jKz5k.html
  artifacts:
    paths:
    - public
  only:
  - master
