title: IPB Pedro Nunes
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://ipbpedronunes.org"

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: :compressed

authors:
  lucas:
    name: Lucas Oliveira
    bio: Sonoplasta e superintendente da Escola Dominical.
    photo: lucas.jpg

  milton:
    name: Pr. Milton Santos
    bio: Presbítero e professor da Escola Dominical.
    photo: milton.jpg

  luiz:
    name: Rev. Luiz Barreto
    bio: Pastor da Igreja Presbiteriana do Brasil de Pedro Nunes
    photo: luiz.png

social:
  instagram: https://www.instagram.com/ipbpedronunesorg/
  facebook: https://www.facebook.com/IpbPedroNunes/

