title: IPB Pedro Nunes
email: your-email@example.com
description: >-
  Bem-vindo(a) ao site da Igreja Presbiteriana do Brasil de Pedro Nunes!
  Nós convidamos você a se juntar a nós para aprender sobre a palavra de Deus.
lang: pt_BR
baseurl: ""
url: "https://ipbpedronunes.org"

paginate: 10
paginate_path: "/blog/page:num/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: :compressed

authors:
  lucas:
    name: Lucas Arantes
    bio: Ajuda a manter o site lá das terras geladas do Canadá.
    photo: lucas.jpg

  milton:
    name: Pr. Milton Santos
    bio: Presbítero.
    photo: milton.jpg

  luiz:
    name: Rev. Luiz Barreto
    bio: Pastor da Igreja Presbiteriana do Brasil de Pedro Nunes
    photo: luiz.png

social:
  instagram: https://www.instagram.com/ipbpedronunesorg/
  facebook: https://www.facebook.com/IpbPedroNunes/
  youtube: https://www.youtube.com/channel/UCRmtMDRb4x7TcZ7AVIFJiyQ

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ipbpedronunes.jpg
