title: IPB Pedro Nunes
email: your-email@example.com
description: >-
  Bem-vindo(a) ao site da Igreja Presbiteriana do Brasil de Pedro Nunes!
  Nós convidamos você a se juntar a nós para aprender sobre a palavra de Deus.
lang: pt_BR
baseurl: ""
url: "https://ipbpedronunes.org"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed

authors:
  lucas:
    name: Lucas Arantes
    bio: Ex-sonoplasta e ex-superintendente da Escola Dominical. Agora vive no Canadá.
    photo: lucas.jpg

  milton:
    name: Pr. Milton Santos
    bio: Presbítero e professor da Escola Dominical.
    photo: milton.jpg

  luiz:
    name: Rev. Luiz Barreto
    bio: Pastor da Igreja Presbiteriana do Brasil de Pedro Nunes
    photo: luiz.png

social:
  instagram: https://www.instagram.com/ipbpedronunesorg/
  facebook: https://www.facebook.com/IpbPedroNunes/

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/ipbpedronunes.jpg
